(defun maxline1 (w i n)
  (if (< i n) (max( maxline1  w (+ i 1) n) (aref w n i)) (aref w n i)))
(defun maxmat1 (w i)
	(if (< (+ i 1)  (array-dimension w 0)) (max (maxline1  w 0 i) (maxmat1 w (+ i 1)))
 (maxline1  w 0 i)
))
(defun maxmat2 (w)
	(maxmat1 w 0)
)
(setq a (make-array '(3 3) :initial-contents '((1 2 3) (4 5 6) (7 8 9))))
(setq b (make-array '(3 3) :initial-contents '((7 8 9) (4 5 6) (1 2 3))))
(setq ñ (make-array '(2 2) :initial-contents '((-1 3) (-3 -2))))
(maxmat2 a)
(maxmat2 b)
(maxmat2 ñ)
